---
title: Luke's Site
tagline: A Site Just For Luke
description: This is where <a href="http://twitter.com/luke" target="_blank">Luke</a>
  Writes
url: https://jolly-goldberg-15ab6c.netlify.app
baseurl: ''
author:
  name: Luke Butler
  url: https://twitter.com/Luke
paginate: 7
exclude:
- README.md
- vendor/bundle
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#A33B3B"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#8D4F4F"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
